webp_A/app/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect
import functools

from app import db
from app.forms import UserCreateForm, UserLoginForm
from app.models import User

bp = Blueprint('auth', __name__, url_prefix = '/auth')

@bp.route('/signup/', methods = ('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username = form.username.data).first()
        if not user:
            user = User(username = form.username.data,
                        password = generate_password_hash(form.password1.data),
                        email = form.email.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('signup.html', form = form)

@bp.route('/login/', methods = ('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username = form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        
        if error is None:
            session.clear()
            session['user_id'] = user.id
            _next = request.args.get('next', '')
            if _next:
                return redirect(_next)
            else:
                return redirect(url_for('main.index'))
        flash(error)
    return render_template('login.html', form = form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None:
            _next = request.url if request.method == 'GET' else ''
            return redirect(url_for('auth.login', next = _next))
        return view(*args, **kwargs)
    return wrapped_view

webp_A/app/views/question_views.py
from flask import Blueprint, render_template, request, url_for, flash, g, session
from werkzeug.utils import redirect
from datetime import datetime
from .. import db

from app.views.auth_views import login_required
from ..models import Item
from ..forms import ItemForm
from PIL import Image
import base64

bp = Blueprint('question', __name__, url_prefix='/question')

@bp.route('/detail_item/<int:item_id>/')
def detail_item(item_id):
    item = Item.query.get_or_404(item_id)
    encoded_img_data = base64.b64encode(item.img)
    item.img = encoded_img_data.decode('utf-8')
    return render_template('item-detail.htm', item = item)

@bp.route('/list_item/')
def _list_item():
    page = request.args.get('page', type = int, default = 1)
    loc = request.args.get('loc', type=str, default='*')
    if loc == '*':
        item_list = Item.query.order_by(Item.create_date.desc())
    else:
        item_list = Item.query.filter_by(location=loc).order_by(Item.create_date.desc())
    item_list = item_list.paginate(page = page, per_page = 6)

    for item in item_list:
        encoded_img_data = base64.b64encode(item.img)
        item.img = encoded_img_data.decode('utf-8')

    return render_template('item-list.htm', item_list = item_list)

@bp.route('/create_item/', methods = ('GET', 'POST'))
def create_item():
    form = ItemForm()
    if request.method == 'POST' and form.validate_on_submit():
        if not g.user:
            return redirect(url_for('auth.login'))
        file = request.files['img']
        data = file.read()
        item = Item(store_name = form.store_name.data, desc = form.desc.data, create_date = datetime.now(), user = g.user,
                            rate = form.rate.data, img=data, location=form.location.data)
        db.session.add(item)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('item-form.htm', form = form)

# @bp.route('/modify/<int:item_id>', methods = ('GET', 'POST'))
# @login_required
# def modify(item_id):
#     item = Item.query.get_or_404(item_id)
#     if g.user != item.user:
#         flash('수정 권한이 없습니다.')
#         return redirect(url_for('question.detail_item', item_id = item_id))
#     if request.method == 'POST':
#         form = ItemForm()
#         if form.validate_on_submit():
#             form.populate_obj(item)
#             item.modify_date = datetime.now()
#             db.session.commit()
#             return redirect(url_for('question.detail_item', item_id = item_id))
#     else:
#         form = ItemForm(obj = item)
#     return render_template('item-form.htm', form = form)

@bp.route('/delete_item/<int:item_id>')
@login_required
def delete_item(item_id):
    item = Item.query.get_or_404(item_id)
    if session['user_id'] != item.user_id:
        flash('삭제 권한이 없습니다')
        return redirect(url_for('question.detail_item', item_id = item_id))
    db.session.delete(item)
    db.session.commit()
    return redirect(url_for('question._list_item'))

webp_A/app/templates/base.html
<!doctype html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jump2Daegu</title>
    <link rel = "stylesheet" href = "{{ url_for('static', filename = 'bootstrap.min.css') }}">
    <link rel = "stylesheet" href = "{{ url_for('static', filename = 'style.css') }}">
</head>
<body>
    <div class="container-fluid">
        <div class="row justify-content-end">
            <div class="col-3 top">
                <a href="#">Sign in</a>
                <a href="#">Sign up</a>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row justify-content-md-center">
            <div class="col-6 title text-align-center">
                JumpToDaegu
            </div>
        </div>
        <nav>
            <div class="row justify-content-md-center">
                <div class="col-6 menu justify-content-around">
                    <a href="#"><div class="nav-item">중구</div></a>
                    <a href="#"><div class="nav-item">북구</div></a>
                    <a href="#"><div class="nav-item">서구</div></a>
                    <a href="#"><div class="nav-item">동구</div></a>
                    <a href="#"><div class="nav-item">남구</div></a>
                </div>
            </div>
            <div class="row justify-content-md-center">
                <div class="col-6 menu justify-content-around">
                    <a href="#"><div class="nav-item">수성구</div></a>
                    <a href="#"><div class="nav-item">달성구</div></a>
                    <a href="#"><div class="nav-item">달성군</div></a>
                </div>
            </div>
        </nav>
    </div>

<nav class = "navbar navbar-expanding-lg navbar-light bg-light border-bottom">
    <div class = "container-fluid">
        <a class = "navbar-brand" href = "{{url_for('main.index') }}"></a>
        <button class = "navbar-toggler" type = "button" 
                data-bs-toggle = "collapse" 
                data-bs-target = "#navbarSupprtedContent"
                aria-controls = "navbarSupprtedContent"
                aria-expanded = "false"
                aria-label = "Toggle navigation">
            <span class = "navbar-toggler-icon"></span>
        </button>
        <div class = "collapse navbar-collapse", id = "navbarSupprtedContent">
            {%if g.user%}
            <ul class = "navbar-nav">
                <li class = "nav-item">
                    <a class = "nav-link" href = "{{url_for('auth.logout')}}">{{g.user.username}}(로그아웃)</a>
                </li>
            </ul>
            {%else%}
            <ul class = "navbar-nav me-auto mb-2 mb-lg-0">
                <li class = "nav-item">
                    <a class = "nav-link" href = "{{url_for('auth.signup')}}">계정생성</a>
                </li>
                <li class = "nav-item">
                    <a class = "nav-link" href = "{{url_for('auth.login')}}">로그인</a>
                </li>
            </ul>
            {%endif%}
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
<script src = "{{ url_for('static', filename = 'bootstrap.min.js') }}"></script>
{%block script%}
{%endblock%}
</body>
</html>

webp_A/app/templates/form_errors.html
<!-- 필드오류 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!-- flash error -->
{%for message in get_flashed_messages()%}
<div class = "alert alert-danger" role = "alert">
    {{message}}
</div>
{%endfor%}

webp_A/app/templates/head.htm
{% block head %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jump2Daegu</title>
    <link rel = "stylesheet" href = "{{ url_for('static', filename = 'bootstrap.min.css') }}">
    <link rel = "stylesheet" href = "{{ url_for('static', filename = 'style.css') }}">
    <script src="https://kit.fontawesome.com/5444416a85.js" crossorigin="anonymous"></script>
{% endblock %}

webp_A/app/templates/header.htm
{% block header %}
<div class="container-fluid">
    <div class="row justify-content-end">
        <div class="col-3 top">
            {% if g.user %}
                <a class = "nav-link" href = "{{url_for('auth.logout')}}">{{g.user.username}}(Logout)</a>
            {% else %}
                <a href="{{url_for('auth.login')}}">Sign in</a>
                <a href="{{url_for('auth.signup')}}">Sign up</a>
            {% endif %}
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row justify-content-md-center">
        <div class="col-6 title text-align-center">
            <a href="{{ url_for('question._list_item') }}">JumpToDaegu</a>
        </div>
    </div>
    <nav>
        <div class="row justify-content-md-center">
            <div class="col-6 menu justify-content-around">
                <a href="{{url_for('question._list_item', loc = '중구') }}"><div class="nav-item">중구</div></a>
                <a href="{{url_for('question._list_item', loc = '북구') }}"><div class="nav-item">북구</div></a>
                <a href="{{url_for('question._list_item', loc = '서구') }}"><div class="nav-item">서구</div></a>
                <a href="{{url_for('question._list_item', loc = '동구') }}"><div class="nav-item">동구</div></a>
                <a href="{{url_for('question._list_item', loc = '남구') }}"><div class="nav-item">남구</div></a>
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-6 menu justify-content-around">
                <a href="{{url_for('question._list_item', loc = '수성구') }}"><div class="nav-item">수성구</div></a>
                <a href="{{url_for('question._list_item', loc = '달성구') }}"><div class="nav-item">달성구</div></a>
                <a href="{{url_for('question._list_item', loc = '달성군') }}"><div class="nav-item">달성군</div></a>
            </div>
        </div>
    </nav>
</div>
{% endblock %}

webp_A/app/templates/index.htm
<!DOCTYPE html>
{% include "head.htm" %}
{% include "header.htm" %}
{% include "item-list.htm" %}
<html lang="en">
<head>
    {% block head %}
    {% endblock %}
</head>
<body>
    {% block header %}
    {% endblock %}
    {% block item_list %}
    {% endblock %}
</body>
</html>

webp_A/app/templates/item-detail.htm
<!DOCTYPE html>
{% include "head.htm" %}
{% include "header.htm" %}
<html lang="en">
<head>
    {% block head %}
    {% endblock %}
</head>
<body>
    {% block header %}
    {% endblock %}
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-5">
                {%if session['user_id'] == item.user_id%}
                 <a href = "{{url_for('question.delete_item', item_id = item.id)}}">
                    <button class = "write">삭제</button></a>
                {%endif%}
                <div class="item-container">
                    <div class="img-container">
                        <img src="data:image/jpeg;base64,{{ item.img }}" class="img-fluid">
                    </div>
                    <div class="metadata">
                        <div class="title">
                            {{ item.store_name }}
                        </div>
                        <div class="rate">
                            {% for i in range(item.rate) %}
                                <i class="fa-solid fa-star"></i>
                            {% endfor %}
                        </div>         
                        </div>
                    <div class="desc">
                            {{ item.desc }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

webp_A/app/templates/item-form.htm
<!DOCTYPE html>
{% include "head.htm" %}
{% include "header.htm" %}
<html lang="en">
<head>
    {% block head %}
    {% endblock %}
</head>
<body>
    {% block header %}
    {% endblock %}
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-5">
                <form method="POST" enctype=multipart/form-data>
                    {{form.csrf_token}}
                    {%if form.errors%}
                        <div class = "alert alert-danger" role = "alert">
                            {%for field, errors in form.errors.items()%}
                            <strong>{{form[field].label}}</strong>
                            <ul>
                                {%for error in errors %}
                                <li>{{error}}</li>
                                {%endfor%}
                            </ul>
                            {%endfor%}
                        </div>
                    {%endif%}

                    <div class = "mb-3">
                        <label for = "store_name">제목</label>
                        <input type = "text" class = "form-control" name = "store_name" id = "store_name" value = "{{form.store_name.data or ''}}">
                    </div>
                    
                    <div class = "mb-3">
                        <label for = "desc">내용</label>
                        <textarea class = "form-control" name = "desc" id = "desc" rows = "10">{{form.desc.data or ''}}</textarea>
                    </div>
                    <div class = "mb-3">
                        <label for = "rate">별점</label>
                        <input type="number" class="form-control" name="rate" id="rate" max="5" min="1">
                    </div>
                    <div class = "mb-3">
                        <label for = "img">이미지</label>
                        <input type="file" class="form-control" name="img" id="img">
                    </div>
                    <div class = "mb-3">
                        {% for subfield in form.location %}
                            <tr>
                                <td>{{ subfield }}</td>
                                <td>{{ subfield.label }}</td>
                            </tr>
                        {% endfor %}
                    </div>
                    
                    <button type = "submit" class = "write"> 저장하기 </button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

webp_A/app/templates/item-list.htm
<!DOCTYPE html>
{% include "head.htm" %}
{% include "header.htm" %}
<html lang="en">
<head>
    {% block head %}
    {% endblock %}
</head>
<body>
    {% block header %}
    {% endblock %}
    <div class="container">
        <div class="row justify-content-end">
            <div class="col-3">
                <a href="{{ url_for('question.create_item') }}"><button class="write">Write</button></a>
            </div>
        </div>
        <div class="row justify-content-md-center">
            {%if item_list%}
            {%for item in item_list.items%}
            
                <div class="col-3" >
                    <a href="{{url_for('question.detail_item', item_id = item.id) }}">
                    <div class="item-container">
                        <div class="img-container">
                            <img src="data:image/jpeg;base64,{{ item.img }}" class="img-fluid">
                        </div>
                        <div class="metadata">
                            <div class="title">
                                {{ item.store_name }}
                            </div>
                            <div class="rate">
                                {% for i in range(item.rate) %}
                                    <i class="fa-solid fa-star"></i>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </a>
                </div>
            
            {%endfor%}
            {%else%}
                등록된 게시물이 없습니다.
            {%endif%}
        </div>
    </div>
</body>
</html>

webp_A/app/templates/login.html
<!DOCTYPE html>
{% include "head.htm" %}
{% include "header.htm" %}

<html lang="en">
<head>
    {% block head %}
    {% endblock %}
</head>
<body>
    {% block header %}
    {% endblock %}
    <div class = "container">
        <h5 class = "my-3 border-bottom pb-2">로그인</h5>
        <form method = "post">
            {{form.csrf_token}}
            {%include "form_errors.html"%}
            <div class = "mb-3">
                <label for = "username">사용자 이름</label>
                <input type = "text" class = "form-control" name = "username" id = "username"
                        value = "{{form.username.data or ''}}">
            </div>
            <div class = "mb-3">
                <label for = "password">비밀번호</label>
                <input type = "password" class = "form-control" name = "password" id = "password"
                        value = "{{form.password.data or ''}}">
            </div>
            <button type = "submit" class = "write">로그인</button>
        </form>
    </div>
    
    
</body>
</html>

webp_A/app/templates/signup.html
<!DOCTYPE html>
{% include "head.htm" %}
{% include "header.htm" %}

<html lang="en">
<head>
    {% block head %}
    {% endblock %}
</head>
<body>
    {% block header %}
    {% endblock %}
    <div class = "container">
        <h5 class = "my-3 border-bottom pb-2">계정 생성</h5>
        <form method = "post">
            {{form.csrf_token}}
            {%include "form_errors.html"%}
            <div class = "mb-3">
                <label for = "username">사용자 이름</label>
                <input type = "text" class = "form-control" name = "username" id = "username"
                        value = "{{form.username.data or ''}}">
            </div>
            <div class = "mb-3">
                <label for = "password1">비밀번호</label>
                <input type = "password" class = "form-control" name = "password1" id = "password1"
                        value = "{{form.password1.data or ''}}">
            </div>
            <div class = "mb-3">
                <label for = "password2">비밀번호 확인</label>
                <input type = "password" class = "form-control" name = "password2" id = "password2"
                        value = "{{form.password2.data or ''}}">
            </div>
            <div class = "mb-3">
                <label for = "email">이메일</label>
                <input type = "text" class = "form-control" name = "email" id = "email"
                        value = "{{form.email.data or ''}}">
            </div>
            <button type = "submit" class = "write">생성하기</button>
        </form>
    </div>
    
    
</body>
</html>